//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EJ04 {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class SettingsEJ04 : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsEJ04 defaultInstance = ((SettingsEJ04)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsEJ04())));
        
        public static SettingsEJ04 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Martin")]
        public string AESSal {
            get {
                return ((string)(this["AESSal"]));
            }
            set {
                this["AESSal"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pFlEmEL5_¡4#pF")]
        public string AESContraseña {
            get {
                return ((string)(this["AESContraseña"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int CesDesplazamiento {
            get {
                return ((int)(this["CesDesplazamiento"]));
            }
        }
    }
}
